<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Admin Panel</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300;400;600;700&display=swap"
      rel="stylesheet"
    />
  </head>

  <body>
    <div class="main__container">
      <div class="main__content">
        <div class="container-sm h-full d-flex justify-content-center" style="height: 100vh">
          <div class="align-self-center">
            <div class="border border-secondary shadow rounded p-5">
              <h2 class="text-center">Admin Panel</h2>
              <form action="/admin/login" method="post">
                <div class="mb-3">
                  <label for="inputLogin" class="form-label">Login</label>
                  <input name="login" type="Login" class="form-control" id="inputLogin" aria-describedby="emailHelp" />
                </div>
                <div class="mb-3">
                  <label for="inputPassword" class="form-label">Password</label>
                  <input name="password" type="password" class="form-control" id="inputPassword" />
                </div>
                <div class="d-grid">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
                <a class="mt-2 text-decoration-none text-center w-full d-block" href="/">Back</a>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
